### ISSUE TITLE
Does this support PNPM?

### ISSUE THREAD

**Issue by Clashsoft** [langrp/gradle-angular-plugin#3]
Does this plugin support the [pnpm](https://github.com/pnpm/pnpm) package manager? Or in general, does it respect `ng config cli.packageManager`?

**Comment by langrp** [comment]
Unfortunately pnpm is not supported. I'd like to provide support for multiple package managers for future releases. As of now the plugin uses `npm`.

**Comment by langrp** [comment]
Support for pnpm added in latest version
