### ISSUE TITLE
Compile with ng build --prod

### ISSUE THREAD

**Issue by assen-krastev** [langrp/gradle-angular-plugin#4]
I didn't find anything in the documentation for building with --prod option, so I've tried this:

angularCli {
  command = 'build'
  arguments = '--prod'
}

but it doesn't work. It still runs "ng build" without "--prod"

**Comment by langrp** [comment]
Thanks for pointing missing documentation. The plugin defines task `compileAngular` which executes `npm` script build. So the build parameters can be defined within `package.json`

```json
  "scripts": {
    "build": "ng build --prod"
  }
```

This part is planned to be configurable and documented. I'd like to let users to choose between executing `package.json` script or running `ng build` with custom arguments.
